### PR TITLE
Config/shell: fix PHPCS command

### PR DESCRIPTION
**Pull request by jrfnl**
(hopefully)

With a bit of luck, this should fix the build for the Comment Hacks repo.

### CODE REVIEW

**Comment by karlijnbok** [comment]
CR 👍 
Should this be tested in some way? @jrfnl

**Comment by jrfnl** [comment]
@karlijnbok Yes, except I'm not sure how. Possibly with the Comment Hacks repo and setting this branch up to be used, but then it would still need to be build by Travis on a dev branch to verify the fix worked. Considering the previous command was broken, I got the impression that this repo is merge & trial & error.

**Review by increddibelly — APPROVED** [review]

**Comment by ghost** [comment]
With the blessing of @increddibelly I'm merging this PR without testing it. Given the simplicity of the fix, that seems a waste of resources. 

I will restart the Travis build on the Comment Hacks repo to verify whether this PR will fix it :)

**Comment by ghost** [comment]
Hmm, I can't restart the build since the Comment Hacks repository was migrated and is now building on travis-ci.com, and no builds have been done there yet (meaning I would need to push a commit to trigger the first build). Let's find out in the future then.

**Pull request merged**
